# Generated by Django 5.2.3 on 2025-07-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_created_by'),
        ('tenants', '0002_alter_tenant_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
