# Generated by Django 5.2.3 on 2025-07-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0002_alter_tenant_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryitem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry_items', to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
