# Generated by Django 5.2.3 on 2025-07-05 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customers', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0002_supplierproduct'),
        ('tenants', '0002_alter_tenant_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accounts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Company Account',
                'verbose_name_plural': 'Company Accounts',
                'ordering': ['tenant', 'account_name'],
                'unique_together': {('tenant', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('IN', 'Receita'), ('EX', 'Despesa')], default='EX', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Financial Category',
                'verbose_name_plural': 'Financial Categories',
                'ordering': ['tenant', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_statuses', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Financial Status',
                'verbose_name_plural': 'Financial Statuses',
                'ordering': ['tenant', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='customers.customer')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_receivable', to='sales.saleorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='tenants.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='financials.financialcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='financials.financialstatus')),
            ],
            options={
                'verbose_name': 'Account Receivable',
                'verbose_name_plural': 'Accounts Receivable',
                'ordering': ['tenant', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_payable', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_payable', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payable', to='tenants.tenant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_payable', to='financials.financialcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_payable', to='financials.financialstatus')),
            ],
            options={
                'verbose_name': 'Account Payable',
                'verbose_name_plural': 'Accounts Payable',
                'ordering': ['tenant', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('BT', 'Bank Transfer'), ('PIX', 'Pix'), ('CHK', 'Check'), ('OTH', 'Other')], default='CASH', max_length=5)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document_object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='financials.companyaccount')),
                ('document_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['tenant', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flows', to='financials.financialcategory')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='financials.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'verbose_name_plural': 'Cash Flows',
                'ordering': ['tenant', '-created_at'],
            },
        ),
    ]
