# Generated by Django 5.2.3 on 2025-07-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatus',
            options={'ordering': ['id'], 'verbose_name': 'Financial Status', 'verbose_name_plural': 'Financial Statuses'},
        ),
    ]
