# Generated by Django 5.2.3 on 2025-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='label',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
