# Generated by Django 5.2.3 on 2025-07-04 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_product_product_cannot_be_its_own_parent'),
        ('tenants', '0002_alter_tenant_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('BT', 'Bank Transfer'), ('PIX', 'Pix'), ('CHK', 'Check'), ('OTH', 'Other')], default='CASH', max_length=5)),
                ('shipping_method', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_track', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='customers.customer')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sale Order',
                'verbose_name_plural': 'Sale Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_order_items', to='products.product')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Sale Order Item',
                'verbose_name_plural': 'Sale Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('color_code', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_statuses', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sale Order Status',
                'verbose_name_plural': 'Sale Order Statuses',
                'ordering': ['sequence_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SaleOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_order_history', to=settings.AUTH_USER_MODEL)),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales.saleorder')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_history', to='sales.saleorderstatus')),
            ],
            options={
                'verbose_name': 'Sale Order History',
                'verbose_name_plural': 'Sale Order Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='saleorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='sales.saleorderstatus'),
        ),
    ]
