# Generated by Django 5.2.3 on 2025-07-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
