# Generated by Django 5.2.3 on 2025-07-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0002_alter_tenant_cnpj'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='product_cannot_be_its_own_parent'),
        ),
    ]
